"""Write docs/api-examples.md: real request/response pairs from the Ramesh story (synthetic data, fake AI)."""

import json
from pathlib import Path

from fastapi.testclient import TestClient

from app.domain.ai import DeterministicFakeAI
from app.main import app

OUT = Path(__file__).resolve().parents[2] / "docs" / "api-examples.md"


def main() -> None:
    parts = ["# API examples — REAL responses from the backend (generated by scripts/dump_api_examples.py)",
             "Build the frontend against these exact shapes. Lists are trimmed to 2 items.\n"]
    with TestClient(app) as c:
        app.state.ai = DeterministicFakeAI()

        def call(method, path, user, body=None, files=None, data=None, expected_status=None):
            h = {"X-Demo-User": user}
            r = c.request(method, "/api/v1" + path, headers=h, json=body, files=files, data=data)
            out = r.json()
            if expected_status is None:
                assert 200 <= r.status_code < 300, f"{method} {path}: HTTP {r.status_code}"
            else:
                assert r.status_code == expected_status, f"{method} {path}: HTTP {r.status_code}"
            shown = out[:2] if isinstance(out, list) else out
            req = f"\nBody: `{json.dumps(body, ensure_ascii=False)}`" if body is not None else ""
            if files:
                req = f"\nmultipart: audio file + form {data}"
            parts.append(f"## {method} {path}  (as `{user}`) → HTTP {r.status_code}{req}\n```json\n"
                         + json.dumps(shown, indent=2, ensure_ascii=False) + "\n```\n")
            return out

        officer = "officer-1"
        call("POST", "/demo/reset", officer)
        ids = call("GET", "/demo/scenario/ramesh", officer)
        call("GET", "/demo/users", officer)
        call("GET", "/me", "patient-user-001")
        call("GET", "/facilities", officer)
        call("GET", "/drugs", officer)
        call("GET", f"/patients/{ids['patient_id']}", "asha-1")
        call("GET", "/patients", "asha-1")
        voice = call("POST", "/cases/voice", "patient-user-001",
                     files={"audio": ("r.webm", b"fake-audio", "audio/webm")}, data={"lang": "hi"})
        fields = voice.get("fields", {}) if isinstance(voice, dict) else {}
        call("POST", "/cases/voice/confirm", "patient-user-001",
             {"fields": fields, "transcript": voice.get("transcript")}, expected_status=422)
        corrected_fields = {**fields, "drug_id": ids["drug_id"], "requested_qty": 30,
                            "household_supply_days": 0,
                            "attempted_at": "2026-09-28T09:00:00Z"}
        case = call("POST", "/cases/voice/confirm", "patient-user-001",
                    {"fields": corrected_fields, "transcript": voice.get("transcript")})
        cid = case["id"]
        call("GET", "/cases", "patient-user-001")
        call("GET", "/cases?status=reported", ids["pharmacist_id"])
        call("POST", f"/cases/{cid}/verify", ids["pharmacist_id"], {"result": "confirmed_stockout", "on_hand": 0})
        call("GET", "/district/overview?district=Suryanagar", officer)
        call("GET", f"/district/series?facility_id={ids['facility_id']}&drug_id={ids['drug_id']}", officer)
        t = call("POST", "/transfers/draft", officer, {"case_id": cid})
        call("GET", "/transfers?status=draft", officer)
        call("GET", f"/transfers/{t['id']}", ids["pharmacist_id"])
        for action, actor in (("approve", officer), ("dispatch", officer), ("receive", ids["pharmacist_id"])):
            call("POST", f"/transfers/{t['id']}/{action}", actor)
        call("POST", f"/cases/{cid}/supply", ids["pharmacist_id"], {"quantity": 10})
        call("POST", f"/cases/{cid}/supply", ids["pharmacist_id"], {"quantity": 20})
        call("POST", f"/cases/{cid}/confirm-received-by-patient", "patient-user-001")
        call("GET", f"/cases/{cid}", officer)
        call("POST", "/stock", ids["pharmacist_id"], {"facility_id": ids["facility_id"], "drug_id": "amlodipine",
                                                      "on_hand": 120, "source": "manual", "batches": [
                                                          {"id": "example-amlodipine-batch", "quantity": 120,
                                                           "expiry_date": "2027-03-01"}]})
        call("GET", f"/stock?facility_id={ids['facility_id']}", ids["pharmacist_id"])
        manual_body = {"patient_id": ids["patient_id"], "drug_id": ids["drug_id"],
                       "requested_qty": 30, "household_supply_days": 0,
                       "attempted_at": "2026-09-28T09:00:00Z", "channel": "manual"}
        cancelled = call("POST", "/cases", "patient-user-001", manual_body)
        call("POST", f"/cases/{cancelled['id']}/cancel", "patient-user-001",
             {"note": "Patient withdrew this synthetic request"})
        unfeasible = call("POST", "/cases", "patient-user-001",
                          {**manual_body, "requested_qty": 100000})
        call("POST", f"/cases/{unfeasible['id']}/verify", ids["pharmacist_id"],
             {"result": "confirmed_stockout", "on_hand": 0})
        call("POST", "/transfers/draft", officer, {"case_id": unfeasible["id"]})
        sync = call("POST", "/sync/batch", "asha-1", {"ops": [{"op_id": "demo-op-1", "method": "POST",
              "path": "/cases", "body": manual_body}]})
        assert sync["results"][0]["status"] == "applied"
        call("GET", "/evaluation/summary", officer)
        call("GET", "/cases/does-not-exist", officer, expected_status=404)
    OUT.write_text("\n".join(parts))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
